output functions checking output type

diff --git a/expect b/expect
--- a/expect
+++ b/expect
@@ -12,6 +12,7 @@ EXPECT_OUTPUT_HEADER_DONE=0
 EXPECT_FAILED_TESTS=()
 EXPECT_TEST_COUNT=0
 EXPECT_TOTAL_TEST_COUNT=0
+EXPECT_OUTPUT_TYPE=tap
 
 #=== FUNCTION =================================================================
 #        NAME: -expect
@@ -24,9 +25,10 @@ EXPECT_TOTAL_TEST_COUNT=0
     local description=$1
     local reason=$2
     [ ! -z "$3" ] && reason=$3
+
     EXPECT_TEST_COUNT=$((EXPECT_TEST_COUNT + 1))
-    echo "ok $EXPECT_TEST_COUNT - $description # SKIP $reason"
-    return 0
+    output:result skip "$EXPECT_TEST_COUNT" "$description" "$reason"
+    [ 0 ]
 }
 
 #=== FUNCTION =================================================================
@@ -46,9 +48,9 @@ expect() {
 
     # TAP test line
     if [[ "$exit_code" -eq "0" ]]; then
-        echo "ok $EXPECT_TEST_COUNT - $description"
+        output:result pass "$EXPECT_TEST_COUNT" "$description"
     else
-        echo "not ok $EXPECT_TEST_COUNT - $description"
+        output:result fail "$EXPECT_TEST_COUNT" "$description"
         EXPECT_FAILED_TESTS+=($EXPECT_TEST_COUNT)
     fi
 
@@ -62,7 +64,10 @@ expect() {
 # PARAMETER 1: message/reason of bail out
 #==============================================================================
 bail_out() {
-    echo "Bail out! $1"
+    case "$EXPECT_OUTPUT_TYPE" in
+        tap) echo "Bail out! $1" ;;
+    esac
+
     exit 1
 }
 
@@ -72,7 +77,35 @@ bail_out() {
 # PARAMETER 1: message/diagnostic
 #==============================================================================
 diagnostic() {
-    echo "# $1"
+    case "$EXPECT_OUTPUT_TYPE" in
+        tap) echo "# $1" ;;
+    esac
+}
+
+#=== FUNCTION =================================================================
+#        NAME: output:result
+# DESCRIPTION: tests result output
+# PARAMETER 1: result (pass, fail, skip)
+# PARAMETER 2: test count
+# PARAMETER 3: test description
+# PARAMETER 3: test directive
+#==============================================================================
+output:result() {
+    local result=$1
+    local count=$2
+    local description=$3
+    local directive=$4
+
+    case "$EXPECT_OUTPUT_TYPE" in
+        tap)
+            case "$result" in
+                fail) echo "not ok $count - $description" ;;
+                pass) echo "ok $count - $description" ;;
+                skip) echo "ok $count - $description - SKIP $directive" ;;
+            esac
+
+            ;;
+    esac
 }
 
 #=== FUNCTION =================================================================
@@ -81,9 +114,14 @@ diagnostic() {
 #==============================================================================
 output:header() {
     if [ "$EXPECT_OUTPUT_HEADER_DONE" -eq 0 ]; then
-        echo "TAP version 13"
-        echo "1..$EXPECT_TOTAL_TEST_COUNT"
-        EXPECT_OUTPUT_HEADER_DONE=1
+        case "$EXPECT_OUTPUT_TYPE" in
+            tap)
+                echo "TAP version 13"
+                echo "1..$EXPECT_TOTAL_TEST_COUNT"
+                EXPECT_OUTPUT_HEADER_DONE=1
+
+                ;;
+        esac
     fi
 }
 
@@ -93,22 +131,27 @@ output:header() {
 #==============================================================================
 output:footer() {
     if [ "$EXPECT_TOTAL_TEST_COUNT" -eq "$EXPECT_TEST_COUNT" ] && [ ${#EXPECT_FAILED_TESTS[@]} -ne 0 ]; then
-        local save_ifs=$IFS
-        local failed_tests_count="${#EXPECT_FAILED_TESTS[@]}"
-        local failed_percentage=$(echo "scale=2; 100 - $failed_tests_count * 100 / $EXPECT_TOTAL_TEST_COUNT" | bc)
-        local failed_fraction="$failed_tests_count/$EXPECT_TOTAL_TEST_COUNT"
-        local failed_list=
+        case "$EXPECT_OUTPUT_TYPE" in
+            tap)
+                local save_ifs=$IFS
+                local failed_tests_count="${#EXPECT_FAILED_TESTS[@]}"
+                local failed_percentage=$(echo "scale=2; 100 - $failed_tests_count * 100 / $EXPECT_TOTAL_TEST_COUNT" | bc)
+                local failed_fraction="$failed_tests_count/$EXPECT_TOTAL_TEST_COUNT"
+                local failed_list=
 
-        IFS=","
-        failed_list="${EXPECT_FAILED_TESTS[*]}"
-        failed_list="${failed_list//,/, }"
-        IFS=$save_ifs
+                IFS=","
+                failed_list="${EXPECT_FAILED_TESTS[*]}"
+                failed_list="${failed_list//,/, }"
+                IFS=$save_ifs
 
-        echo
-        echo "FAILED tests $failed_list"
-        echo "Failed $failed_fraction tests, $failed_percentage% okay"
+                echo
+                echo "FAILED tests $failed_list"
+                echo "Failed $failed_fraction tests, $failed_percentage% okay"
 
-        exit 1
+                exit 1
+
+            ;;
+        esac
     fi
 }
 
