adding pretty output

diff --git a/expect b/expect
--- a/expect
+++ b/expect
@@ -58,7 +58,6 @@ expect() {
     EXPECT_TEST_COUNT=$((EXPECT_TEST_COUNT + 1))
     output:header
 
-    # TAP test line
     if [[ "$exit_code" -eq "0" ]]; then
         output:result pass "$EXPECT_TEST_COUNT" "$description"
     else
@@ -117,6 +116,15 @@ output:result() {
             esac
 
             ;;
+
+        pretty)
+            case "$result" in
+                fail) echo "  $(tput bold)$(tput setaf 1)✕$(tput sgr0) $(tput setaf 7)$description$(tput sgr0)" ;;
+                pass) echo "  $(tput bold)$(tput setaf 2)✓$(tput sgr0) $(tput setaf 7)$description$(tput sgr0)" ;;
+                skip) echo "  $(tput bold)$(tput setaf 3)-$(tput sgr0) $(tput setaf 7)$description$(tput sgr0)" ;;
+            esac
+
+            ;;
     esac
 }
 
@@ -127,13 +135,18 @@ output:result() {
 output:header() {
     if [ "$EXPECT_OUTPUT_HEADER_DONE" -eq 0 ]; then
         case "$EXPECT_OUTPUT_TYPE" in
+            pretty)
+                echo
+                ;;
+
             tap)
                 echo "TAP version 13"
                 echo "1..$EXPECT_TOTAL_TEST_COUNT"
-                EXPECT_OUTPUT_HEADER_DONE=1
 
                 ;;
         esac
+
+        EXPECT_OUTPUT_HEADER_DONE=1
     fi
 }
 
@@ -142,34 +155,41 @@ output:header() {
 # DESCRIPTION: TAP failed tests summary
 #==============================================================================
 output:footer() {
-    if [ "$EXPECT_TOTAL_TEST_COUNT" -eq "$EXPECT_TEST_COUNT" ] && [ ${#EXPECT_FAILED_TESTS[@]} -ne 0 ]; then
+    if [ "$EXPECT_TOTAL_TEST_COUNT" -eq "$EXPECT_TEST_COUNT" ]; then
         case "$EXPECT_OUTPUT_TYPE" in
-            tap)
-                local save_ifs=$IFS
-                local failed_tests_count="${#EXPECT_FAILED_TESTS[@]}"
-                local failed_percentage=$(echo "scale=2; 100 - $failed_tests_count * 100 / $EXPECT_TOTAL_TEST_COUNT" | bc)
-                local failed_fraction="$failed_tests_count/$EXPECT_TOTAL_TEST_COUNT"
-                local failed_list=
-
-                IFS=","
-                failed_list="${EXPECT_FAILED_TESTS[*]}"
-                failed_list="${failed_list//,/, }"
-                IFS=$save_ifs
-
+            pretty)
                 echo
-                echo "FAILED tests $failed_list"
-                echo "Failed $failed_fraction tests, $failed_percentage% okay"
+                ;;
 
-                exit 1
+            tap)
+                if [ ${#EXPECT_FAILED_TESTS[@]} -ne 0 ]; then
+                    local save_ifs=$IFS
+                    local failed_tests_count="${#EXPECT_FAILED_TESTS[@]}"
+                    local failed_percentage=$(echo "scale=2; 100 - $failed_tests_count * 100 / $EXPECT_TOTAL_TEST_COUNT" | bc)
+                    local failed_fraction="$failed_tests_count/$EXPECT_TOTAL_TEST_COUNT"
+                    local failed_list=
 
-            ;;
+                    IFS=","
+                    failed_list="${EXPECT_FAILED_TESTS[*]}"
+                    failed_list="${failed_list//,/, }"
+                    IFS=$save_ifs
+
+                    echo
+                    echo "FAILED tests $failed_list"
+                    echo "Failed $failed_fraction tests, $failed_percentage% okay"
+                fi
+
+                ;;
         esac
+
+        if [ ${#EXPECT_FAILED_TESTS[@]} -ne 0 ]; then
+            exit 1
+        fi
     fi
 }
 
 #=== FUNCTION =================================================================
 #        NAME: tests:counter
-# DESCRIPTION: TAP failed tests summary
 # PARAMETER 1: file to count tests in
 #==============================================================================
 tests:counter() {
